export const routePaths = {
  account: '/account',
  accountAddresses: '/account/addresses',
  accountAwards: '/account/awards',
  accountBrand: '/account/brand',
  accountCares: '/account/avs-cares',
  accountChangePassword: '/account/change-password',
  accountCollectionService: '/account/returnbox',
  accountDeleteAccount: '/account/delete-account',
  accountDeliveryMembership: '/account/delivery-membership',
  accountFavourites: '/account/myfavourites',
  accountKitchen: '/account/avs-kitchen',
  accountMedia: '/account/media',
  accountOrders: '/account/orderhistory',
  accountQuality: '/account/quality',
  accountReferFriends: '/account/refer-friends',
  accountRegulars: '/account/myregulars',
  accountRewardPoints: '/account/reward-points',
  accountStatus: '/account/status',
  accountShoppingList: '/account/myshoppinglist',
  accountStatement: '/account/mystatement',
  accountStory: '/account/story',
  accountVouchers: '/account/myvouchers',
  accountVision: '/account/vision',
  accountWallet: '/account/mywallet',
  accountWioBank: '/account/wio-bank',
  auth: {
    forgotPassword: '/auth/forgot-password',
    login: '/auth/login',
    register: '/auth/register',
  },
  cart: '/cart',
  catalog: '/catalog',
  checkout: '/checkout',
  home: '/',
  notFound: '*',
  orders: '/orders',
  productDetails: '/products/:productId',
  tenantAdmin: {
    categories: '/admin/categories',
    customers: '/admin/customers',
    dashboard: '/admin/dashboard',
    deliveryFees: '/admin/delivery-fees',
    orders: '/admin/orders',
    products: '/admin/products',
    promotions: '/admin/promotions',
  },
} as const;
