export const endpoints = {
  addresses: {
    item: (id: string) => `/addresses/${id}`,
    list: '/addresses',
  },
  auth: {
    bootstrap: '/auth/bootstrap',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    password: '/auth/password',
    requestOtp: '/auth/otp/request',
    register: '/auth/register',
  },
  admin: {
    carousel: '/admin/carousel',
    carouselSlide: (id: string) => `/admin/carousel/${id}`,
    categories: '/admin/categories',
    category: (id: string) => `/admin/categories/${id}`,
    customers: '/admin/customers',
    dashboard: '/admin/dashboard',
    deliveryFee: (id: string) => `/admin/delivery-fees/${id}`,
    deliveryFees: '/admin/delivery-fees',
    orderStats: '/admin/orders/stats',
    orderStatus: (id: string) => `/admin/orders/${id}/status`,
    orders: '/admin/orders',
    pageSegment: (id: string) => `/admin/page-segments/${id}`,
    pageSegments: '/admin/page-segments',
    product: (id: string) => `/admin/products/${id}`,
    productBulk: '/admin/products/bulk',
    products: '/admin/products',
    productSectionAssignment: (id: string) => `/admin/product-sections/assignments/${id}`,
    productSectionAssignments: '/admin/product-sections/assignments',
    productSections: '/admin/product-sections',
    profile: '/admin/profile',
    promotion: (id: string) => `/admin/promotions/${id}`,
    promotions: '/admin/promotions',
    region: (id: string) => `/admin/regions/${id}`,
    regions: '/admin/regions',
    secondaryCategories: '/admin/secondary-categories',
    secondaryCategory: (id: string) => `/admin/secondary-categories/${id}`,
    storefrontIcon: (id: string) => `/admin/storefront-icons/${id}`,
    storefrontIcons: '/admin/storefront-icons',
    township: (id: string) => `/admin/townships/${id}`,
    townships: '/admin/townships',
    user: (id: string) => `/admin/users/${id}`,
    users: '/admin/users',
    walletTopUpApprove: (id: string) => `/admin/wallet-topups/${id}/approve`,
    walletTopUpReject: (id: string) => `/admin/wallet-topups/${id}/reject`,
    walletTopUps: '/admin/wallet-topups',
  },
  categories: {
    list: '/categories',
  },
  favorites: {
    list: '/favorites',
    toggle: (productId: string) => `/favorites/${productId}/toggle`,
  },
  locations: {
    myanmar: '/locations/myanmar',
  },
  orders: {
    deliveryQuote: '/orders/delivery-quote',
    list: '/orders',
  },
  products: {
    details: (productId: string) => `/products/${productId}`,
    list: '/products',
  },
  storefront: {
    categories: '/storefront/categories',
    carousel: '/storefront/carousel',
    headerSettings: '/storefront/header-settings',
    icons: '/storefront/icons',
    pageSegment: (id: string) => `/storefront/page-segments/${id}`,
    pageSegments: '/storefront/page-segments',
    productSections: '/storefront/product-sections',
    secondaryCategories: '/storefront/secondary-categories',
  },
  shoppingLists: {
    item: (id: string) => `/shopping-lists/${id}`,
    list: '/shopping-lists',
    toggleProduct: (id: string, productId: string) =>
      `/shopping-lists/${id}/products/${productId}/toggle`,
  },
  tenants: {
    create: '/tenants',
    details: (tenantId: string) => `/tenants/${tenantId}`,
    list: '/tenants',
  },
  wallet: {
    summary: '/wallet',
    topUps: '/wallet/topups',
  },
};
