export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    requestOtp: '/auth/otp/request',
    register: '/auth/register',
  },
  admin: {
    carousel: '/admin/carousel',
    carouselSlide: (id: string) => `/admin/carousel/${id}`,
    categories: '/admin/categories',
    category: (id: string) => `/admin/categories/${id}`,
    customers: '/admin/customers',
    dashboard: '/admin/dashboard',
    deliveryFee: (id: string) => `/admin/delivery-fees/${id}`,
    deliveryFees: '/admin/delivery-fees',
    orderStats: '/admin/orders/stats',
    orderStatus: (id: string) => `/admin/orders/${id}/status`,
    orders: '/admin/orders',
    product: (id: string) => `/admin/products/${id}`,
    productBulk: '/admin/products/bulk',
    products: '/admin/products',
    productSectionAssignment: (id: string) => `/admin/product-sections/assignments/${id}`,
    productSectionAssignments: '/admin/product-sections/assignments',
    productSections: '/admin/product-sections',
    profile: '/admin/profile',
    promotion: (id: string) => `/admin/promotions/${id}`,
    promotions: '/admin/promotions',
    storefrontIcon: (id: string) => `/admin/storefront-icons/${id}`,
    storefrontIcons: '/admin/storefront-icons',
  },
  categories: {
    list: '/categories',
  },
  orders: {
    list: '/orders',
  },
  products: {
    details: (productId: string) => `/products/${productId}`,
    list: '/products',
  },
  storefront: {
    carousel: '/storefront/carousel',
    headerSettings: '/storefront/header-settings',
    icons: '/storefront/icons',
    productSections: '/storefront/product-sections',
  },
};
